### ISSUE TITLE
how i do it (in german)

### ISSUE THREAD

**Issue by diplix** [343max/bring-scanner#1]
ich habe schon seit ner ganzen weile nen barcode scanner am kühlschrank hängen, der wiederum an nem pi-zero hängt der die barcodes bisher immer zu meinem „[barcode-buddy](https://github.com/Forceu/barcodebuddy)“ geschickt hat. der schaut die barcodes entweder in [grocy](https://github.com/grocy/grocy) nach oder in einer der grossen barcode datenbanken.

was für mich nie wirklich funktioniert hat war der „intended use“, nämlich die bestandsverwaltung von lebensmitteln mit grocy. das funktioniert einfach nicht auf dauer. auch der „intended use“ von barcode buddy mit verschiedenen modi, mit denen man gescannte artikel als verbraucht, gekauft, geöffnet oderverdorben an grocy weitergeben konnte, hat nie funktioniert.

einzig und allein die verwaltung meines (kuh) milch-bestands hat funktioniert, hab ich hier mal beschrieben: https://mstdn.io/@ix/111398037387314478

vorgestern hatte ich eine idee, wie der scanner sich doch nützlich machen kann und die liess sich mit den vorhandenen mitteln (home assistant mit konfigurierter bring-integration, barcode buddy, grocy) auch schnell umsetzen.

1. ab jetzt meldet der barcode-scanner die barcodes per webhook an home assistant
2. der prüft über eine rest-abfrage bei grocy den barcode
3. wenn der gescannte barcode ein milch-barcode ist, wird der alte ablauf ausgelöst (barcode an barcode buddy, der den bestand in grocy um eine tüte milch reduziert)
4. wenn der gescannte barcode grocy unbekannt ist, wird der barcode auch an barcode buddy (BCB) weitergegeben. BCB macht das nachschlagen und eintragen des barcodes in grocy sehr einfach, BCB dient damit quasi als datenbank-frontend für die barcode-datenbank grocy.
5. wenn der gescannte barcoe bekannt ist, wird der produktname aus der rest-query genommen und an bring weitergegeben und landet damit auf der einkaufsliste.

tl;dr: mit einer einzigen automation und zwei hilfsprogrammen (BCB und grocy) landen alle produkte die ich scanne auf der bring einkaufsliste. grocy ist dabei eine hervorragende und leicht abzufragende barcode datenbank

```
alias: barcode scan verarbeiten
description: ""
trigger:
  - platform: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: barcode-scan-verarbeiten-ANsgKiwzP7iVbWxiEC1SWgJq
condition: []
action:
  - service: rest_command.grocy_get_product_by_barcode
    metadata: {}
    data:
      barcode: "{{trigger.data.barcode}}"
    response_variable: grocy_response
    alias: Barcode → Grocy Produkt
  - if:
      - condition: template
        value_template: "{{ grocy_response['status'] == 200 }}"
        alias: Barcode gefunden?
    then:
      - alias: Parse data
        variables:
          product_name: "{{ grocy_response.content.product.name }}"
      - if:
          - condition: template
            value_template: "{{ grocy_response.content.product.name == 'Milch' }}"
            alias: Wenn Milch, dann Barcodebuddy
        then:
          - service: shell_command.curl
            data:
              url: http://192.168.1.232:8085/index.php?add={{trigger.data.barcode}}
              method: get
            alias: Barcode weiter zu Barcodebudy
        else:
          - service: todo.add_item
            metadata: {}
            data:
              item: "{{ grocy_response.content.product.name }}"
            target:
              entity_id: todo.zuhause
          - service: snips.say
            metadata: {}
            data:
              site_id: ivanka
              text: "{{ grocy_response.content.product.name }} hinzugefügt."
            alias: snips .say [Produkt] hinzugefügt
        alias: Milch zu Barcodebuddy, alles andere zur Einkaufsliste
    else:
      - service: shell_command.curl
        data:
          url: http://192.168.1.232:8085/index.php?add={{trigger.data.barcode}}
          method: get
        alias: Barcode weiter zu Barcodebudy
mode: single
```
